"""projects table updated

Revision ID: cef31676a30b
Revises: 64e7b2925273
Create Date: 2018-08-20 21:56:18.882077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef31676a30b'
down_revision = '64e7b2925273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('project', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('project', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('completed', sa.BOOLEAN(), nullable=False))
    op.drop_column('project', 'status')
    op.drop_column('project', 'category')
    # ### end Alembic commands ###
